name: 'Hello World'
description: 'Greeting and time check'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time of the greeting'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.who-to-greet }}