name: 'Hello World'
description: 'Greeting and time check'
inputs:
  infiles:
    description: input files
    required: true
  outdir:
    description: output directory
    required: true
outputs:
  time:
    description: 'The time'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.infiles }}
    - ${{ inputs.outdir }}
