name: "PlantUML Generator"
description: "Generates diagrams using PlantUML"
inputs:
  infiles:
    description: input files
    required: true
  outdir:
    description: output directory
    required: true
  type:
    description: output type
    required: false
    default: png
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.infiles }}
    - ${{ inputs.outdir }}
    - ${{ inputs.type }}
