name: 'Hello World'
description: 'Greeting and time check'
inputs:
  args:
    description: args for planuml
    required: true
outputs:
  time:
    description: 'The time'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.args }}
