@startuml Faction Turn States

state "TurnMode" as TM

[*] --> TM : TurnModeButton
TM : Turn actions become visible

state Attacking {
  state AttackMode <<entryPoint>>
  state Cancel <<exitPoint>>
  state DoneAttack <<exitPoint>>
  state "PrepareAttack" as PrepA
  state "AttackerSelected" as ASel
  state "TargetSelected" as TSel
  state "DefenderSelected" as DSel
  state "AttackPrepared" as APrep

  TM --> AttackMode : AttackButtonClick
  AttackMode --> PrepA
  PrepA -right-> Cancel : Back/Cancel
  
  PrepA --> ASel : SelectAttackingAsset
  ASel --> PrepA : Back
  ASel -right-> Cancel : Cancel
  
  ASel --> TSel : SelectTargetFaction
  TSel --> ASel : Back
  TSel --> Cancel : Cancel

  TSel --> DSel : SelectDefender
  DSel --> TSel : Back
  DSel -right-> Cancel : Cancel

  DSel --> APrep : ClickDone
  APrep --> DSel : Back
  APrep -right-> Cancel : Cancel

  APrep --> AttackCompute : ConfirmAttack
  AttackCompute : Computing results

  AttackCompute --> Attacked : FinishedComputation
  Attacked : Show results

  Attacked --> ApplyResults : Confirm
  Attacked -right-> Cancel : Cancel
  ApplyResults : Update HP for targets

  ApplyResults --> PrepA : OK
  PrepA --> DoneAttack : Finished



  Cancel --> TM
  DoneAttack --> TM
}






@enduml