@startuml Faction Turn States

state "TurnMode" as TM
state "FactionSelected" as FS
state "AssetSelected" as ASel

[*] --> FS : SelectFaction
FS : Turn Mode button enabled
FS --> TM : EnterTurnMode
TM : Turn actions become visible

TM --> ASel : SelectAsset
ASel : Turn actions enabled

state "TargetSelected" as TSel
state "DefenderSelected" as DSel
state "ComputingAttack" as AComp
state "AttackComputationDone" as ACDone
state "ResultsApplied" as RA
state "PrepareNext" as PN

ASel --> TSel : SelectTarget
TSel --> DSel : SelectDefender
DSel --> AComp : ConfirmAttack
AComp --> ACDone : ComputedResult
ACDone --> [*] : Cancel
ACDone --> RA : Confirm
RA --> [*] : LastAsset
RA : Disables selected asset
RA : (cannot attack again)
RA --> PN : MoreAssetsAvailable
PN --> ASel : SelectedAsset

@enduml