@startuml Faction Turn Use Ability States
hide empty description

state "FactionSelected" as FS : Turn Mode button enabled
state "TurnMode" as TM : Turn actions become visible
state "AssetSelected" as ASel : Turn actions enabled
state cancelled <<start>>
state "Type?" as type <<choice>>
state "Move Self?" as self <<choice>>
state "Find Destination" as FD
state "More Assets?" as more <<choice>>
state "Charged Cost" as CC1
state "Charged Cost" as CC2
state "Meets Threshold" as enough <<choice>>
state "WillRollDice" as WRD1
state "WillRollDice" as WRD2
state "Should Roll" as toroll <<choice>>

state MoveEnd <<end>>
state DisEnd <<end>>
state HarvEnd <<end>>

[*] --> FS : SelectFaction
FS --> TM : EnterTurnMode
cancelled -> TM : from Cancelled
TM --> ASel : SelectAsset
ASel --> type : UseAbilityClick

type --> self : Type=Move
self --> FD : Self
self -> FindOthers : Others
FindOthers --> FD : Selected Asset(s)
FindOthers -[#red,bold]-> FindOthers : InvalidSelection
FindOthers --> MoveEnd : Cancel
FD -[#red,bold]-> FD : InvalidDestination
FD --> CC1 : SelectDestination
FD --> MoveEnd : Cancel
CC1 --> more : ConfirmPayment\n/deduct cost
CC1 -> MoveEnd : Cancel

type --> toroll : Type=Discount
toroll -> WRD2 : ShouldRoll
WRD2 --> FindPurchase : RollDice
WRD2 --> DisEnd : Cancel
toroll --> FindPurchase : ShouldNotRoll
FindPurchase --> CC2 : SelectAsset
FindPurchase -> DisEnd : Cancel
CC2 --> more : PaidCost
CC2 -> DisEnd : Cancel

type --> WRD1 : Type=Harvest
WRD1 --> enough : RollDice
WRD1 -> HarvEnd : Cancel
enough --> more : BelowThreshold
enough -> GetsPaid : AboveThreshold
GetsPaid --> more : AcceptPayment
GetsPaid -> HarvEnd : Cancel

more -> FindNext : More Usable Assets
more --> [*] : Last Asset
FindNext -> TM

@enduml