@startuml Buy Asset States
hide empty description

state "FactionSelected" as FS : Turn Mode button enabled
state "TurnMode" as TM : Turn actions become visible

[*] -> FS : SelectFaction
FS -> TM : EnterTurnMode
TM -> AssetPrompt : BuyAssetClick
AssetPrompt --> [*] : SelectAsset\n/Charge Faction
AssetPrompt -[#red,bold]-> AssetPrompt : NotEnoughCredits
AssetPrompt -> TM : Cancel

@enduml