name: CI Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.plantuml"
      - "**/*.md"
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: "npm"
      - run: npm install
      - run: npm run build
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: build
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: "npm"
      - run: npm install
      - run: npm run ci-test -- --coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  chromatic:
    # FIXME: disabled for now until storybook works again
    if: false
    name: Chromatic Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: "npm"
      - run: npm install
      - name: Publish to Chromatic
        uses: chromaui/action@bc2d84ad2b60813a67d995c5582d696104a19383 # v13.3.2
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
