name: CI Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.15.1
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npm run ci-test
      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: build
  diagrams:
    name: Diagrams
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate PNG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
          args: -v -tpng -o "png" "design"
      - name: 'Upload Diagrams'
        uses: actions/upload-artifact@v3
        with:
          name: diagrams
          path: png
