on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
name: CI Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.15.1
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npm run ci-test
