@startuml Login Logout States
hide empty description

state LoggedOut #LightBlue
state LoggingIn #LightSeaGreen : Showing login dialog
LoggingIn : maybe showing error message
state LoginWaiting #LightGreen : still showing login dialog
state LoggingOut #LightSeaGreen : Showing confirmation dialog
state LogoutWaiting #LightGreen
state Registering #LightSeaGreen : Showing registration dialog
Registering : maybe showing error message
state Registered #LightSeaGreen : Email validation instructions
state RegisterWaiting #LightGreen
RegisterWaiting: still showing registration dialog
state verify <<choice>>
state NeedsVerification #LightSeaGreen : show instruction dialog\nwith resend link
state SendVerificationWaiting #LightGreen
state SendVerificationError #Salmon : show error dialog
state LoggedIn #LightBlue
state PasswordResetting #LightSeaGreen : show dialog to confirm/cancel
state PasswordResetWaiting #LightGreen
state PasswordResetError #Salmon : show error dialog
state PasswordResetSent #LightSeaGreen : notification dialog

LoggedOut --> LoggingIn : RequestLogin
LoggingIn --> LoginWaiting : DoLogin
LoginWaiting --> verify : Success
verify --> LoggedIn : Verified
verify --> NeedsVerification : Unverified
NeedsVerification --> LoggingIn : Close
NeedsVerification --> SendVerificationWaiting : SendVerification
LoggingIn --> LoggedOut : Cancel
LoggedIn --> LoggingOut : RequestLogout
LoggingOut --> LoggedIn : Cancel
LoggingOut --> LogoutWaiting : DoLogout
LogoutWaiting --> LoggedOut : Success
LogoutWaiting --> LoggedIn : Failure
LoginWaiting --> LoggingIn : Failure
LoggingIn --> Registering : RequestRegister
Registering --> RegisterWaiting : DoRegister
RegisterWaiting --> SendVerificationWaiting : Success
RegisterWaiting --> Registering : Failure
Registered --> LoggingIn : RequestLogin
Registering --> LoggingIn : Cancel
SendVerificationWaiting --> SendVerificationError : Failure
SendVerificationWaiting --> Registered : Success
LoggingIn --> PasswordResetting : RequestPasswordReset
PasswordResetting --> LoggingIn : Cancel
PasswordResetting --> PasswordResetWaiting : SendPasswordReset
PasswordResetWaiting --> PasswordResetSent : Success
PasswordResetWaiting --> PasswordResetError : Failure
PasswordResetSent --> LoggingIn : Close
PasswordResetError --> LoggingIn : Close
SendVerificationError --> LogoutWaiting : Close

@enduml