@startuml Login Logout States
hide empty description

state LoggingIn : Showing login dialog
state LoginWaiting : waiting on server
LoginWaiting : still showing login dialog
state LoginError : Showing error message in login dialog
state LoggingOut : Showing confirmation dialog
state Registering : Showing registration dialog
state Registered : Email validation instructions
state RegisterError : Showing error message 
RegisterError: still showing registration dialog
state RegisterWaiting : waiting on server
state LogoutWaiting : waiting on server
state LoggedOut


LoggedOut --> LoggingIn : LoginClick
LoggingIn -left-> LoginWaiting : LoginButtonClick
LoginWaiting -left-> LoggedIn : LoginSuccess
LoggingIn --> LoggedOut : CancelClick
LoggedIn --> LoggingOut : LogoutClick
LoggingOut --> LoggedIn : CancelClick
LoggingOut --> LogoutWaiting : LogoutConfirm
LogoutWaiting --> LoggedOut : LogoutSuccess
LogoutWaiting --> LoggedIn : LogoutFailure
LoginWaiting --> LoginError : LoginFailure
LoginError --> LoggedOut : LoginErrorOkClick
LoggingIn --> Registering : RegisterClick
Registering --> RegisterWaiting : RegisterConfirm
RegisterWaiting --> Registered : RegisterSuccess
RegisterWaiting --> RegisterError : RegisterFailure
RegisterError --> LoggedOut : RegisterErrorOkClick
Registered --> LoggingIn : RegisteredOkClick
Registering --> LoggedOut : CancelClick


@enduml